name: Intersnhip
description: A Flutter app with login, signup, Google Sign In, and JWT token auth.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.11
  js: ^0.7.2
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  google_sign_in: ^6.1.0
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/login.jpg
    - assets/images/signup.jpg
    - assets/images/app.png